// Full curriculum for: Complete Data Science, Machine Learning, DL, NLP Bootcamp
// By Krish Naik | 63 sections • 429 lectures • 99h 9m
// Source: https://www.udemy.com/course/complete-machine-learning-nlp-bootcamp-mlops-deployment/

export interface Lecture {
  id: string;
  title: string;
  duration: string; // "mm:ss" or "hh:mm:ss"
  durationMinutes: number;
}

export interface Section {
  id: number;
  title: string;
  lectures: Lecture[];
  totalLectures: number;
  totalDuration: string;
  totalMinutes: number;
}

// Helper to generate lecture stubs for sections where we have counts but not individual names
function generateLectures(sectionId: number, count: number, titles: string[], avgMinutes: number): Lecture[] {
  return titles.slice(0, count).map((title, i) => ({
    id: `s${sectionId}-l${i + 1}`,
    title,
    duration: `${avgMinutes}:00`,
    durationMinutes: avgMinutes,
  }));
}

export const COURSE_SECTIONS: Section[] = [
  {
    id: 1,
    title: "Getting Started",
    totalLectures: 4,
    totalDuration: "27min",
    totalMinutes: 27,
    lectures: [
      { id: "s1-l1", title: "Welcome To The Course", duration: "2:44", durationMinutes: 3 },
      { id: "s1-l2", title: "Complete Materials", duration: "0:04", durationMinutes: 1 },
      { id: "s1-l3", title: "Anaconda Installation", duration: "11:34", durationMinutes: 12 },
      { id: "s1-l4", title: "Getting Started With VS Code", duration: "12:53", durationMinutes: 13 },
    ],
  },
  {
    id: 2,
    title: "Python Programming Language",
    totalLectures: 8,
    totalDuration: "1hr 24min",
    totalMinutes: 84,
    lectures: generateLectures(2, 8, [
      "Introduction to Python",
      "Variables and Data Types",
      "Strings in Python",
      "String Operations and Methods",
      "Numbers and Type Casting",
      "User Input and Type Conversion",
      "Operators in Python",
      "Python Practice Problems",
    ], 11),
  },
  {
    id: 3,
    title: "Python Control Flow",
    totalLectures: 3,
    totalDuration: "49min",
    totalMinutes: 49,
    lectures: generateLectures(3, 3, [
      "If-Else Conditional Statements",
      "For Loops and While Loops",
      "Loop Control - Break, Continue, Pass",
    ], 16),
  },
  {
    id: 4,
    title: "Inbuilt Data Structures In Python",
    totalLectures: 9,
    totalDuration: "2hr 9min",
    totalMinutes: 129,
    lectures: generateLectures(4, 9, [
      "Lists in Python",
      "List Operations and Methods",
      "Tuples in Python",
      "Sets in Python",
      "Set Operations",
      "Dictionaries in Python",
      "Dictionary Methods",
      "List Comprehension",
      "Nested Data Structures",
    ], 14),
  },
  {
    id: 5,
    title: "Functions In Python",
    totalLectures: 6,
    totalDuration: "1hr 22min",
    totalMinutes: 82,
    lectures: generateLectures(5, 6, [
      "Introduction to Functions",
      "Function Parameters and Arguments",
      "Default and Keyword Arguments",
      "Lambda Functions",
      "Map, Filter, Reduce",
      "Recursion",
    ], 14),
  },
  {
    id: 6,
    title: "Function Practice Questions",
    totalLectures: 3,
    totalDuration: "20min",
    totalMinutes: 20,
    lectures: generateLectures(6, 3, [
      "Practice Problem 1",
      "Practice Problem 2",
      "Practice Problem 3",
    ], 7),
  },
  {
    id: 7,
    title: "Inbuilt Data Structure - Practice Questions",
    totalLectures: 3,
    totalDuration: "20min",
    totalMinutes: 20,
    lectures: generateLectures(7, 3, [
      "Practice Problem 1",
      "Practice Problem 2",
      "Practice Problem 3",
    ], 7),
  },
  {
    id: 8,
    title: "Importing, Creating Modules And Packages",
    totalLectures: 3,
    totalDuration: "35min",
    totalMinutes: 35,
    lectures: generateLectures(8, 3, [
      "Importing Modules",
      "Creating Custom Modules",
      "Packages and __init__.py",
    ], 12),
  },
  {
    id: 9,
    title: "File Handling In Python",
    totalLectures: 3,
    totalDuration: "26min",
    totalMinutes: 26,
    lectures: generateLectures(9, 3, [
      "Reading Files",
      "Writing Files",
      "Working with CSV and JSON",
    ], 9),
  },
  {
    id: 10,
    title: "Exception Handling In Python",
    totalLectures: 2,
    totalDuration: "25min",
    totalMinutes: 25,
    lectures: generateLectures(10, 2, [
      "Try, Except, Finally",
      "Custom Exceptions",
    ], 13),
  },
  {
    id: 11,
    title: "Object Oriented Programming",
    totalLectures: 10,
    totalDuration: "2hr 15min",
    totalMinutes: 135,
    lectures: generateLectures(11, 10, [
      "Introduction to OOP",
      "Classes and Objects",
      "Constructor (__init__)",
      "Instance and Class Variables",
      "Methods - Instance, Class, Static",
      "Inheritance",
      "Multiple Inheritance",
      "Polymorphism",
      "Encapsulation",
      "Abstraction",
    ], 14),
  },
  {
    id: 12,
    title: "Iterators and Generators",
    totalLectures: 4,
    totalDuration: "40min",
    totalMinutes: 40,
    lectures: generateLectures(12, 4, [
      "Iterators in Python",
      "Creating Custom Iterators",
      "Generators and Yield",
      "Generator Expressions",
    ], 10),
  },
  {
    id: 13,
    title: "Numpy",
    totalLectures: 8,
    totalDuration: "1hr 45min",
    totalMinutes: 105,
    lectures: generateLectures(13, 8, [
      "Introduction to Numpy",
      "Numpy Arrays",
      "Array Indexing and Slicing",
      "Array Operations",
      "Broadcasting",
      "Mathematical Functions",
      "Statistical Functions",
      "Numpy Practice",
    ], 13),
  },
  {
    id: 14,
    title: "Pandas",
    totalLectures: 12,
    totalDuration: "2hr 30min",
    totalMinutes: 150,
    lectures: generateLectures(14, 12, [
      "Introduction to Pandas",
      "Series",
      "DataFrame Creation",
      "Reading CSV/Excel Files",
      "DataFrame Indexing",
      "DataFrame Operations",
      "Handling Missing Data",
      "GroupBy Operations",
      "Merge, Join, Concat",
      "Pivot Tables",
      "Apply and Map Functions",
      "Pandas Practice",
    ], 13),
  },
  {
    id: 15,
    title: "Matplotlib",
    totalLectures: 6,
    totalDuration: "1hr 10min",
    totalMinutes: 70,
    lectures: generateLectures(15, 6, [
      "Introduction to Matplotlib",
      "Line Plots",
      "Bar Charts and Histograms",
      "Scatter Plots",
      "Subplots and Customization",
      "Saving Figures",
    ], 12),
  },
  {
    id: 16,
    title: "Seaborn",
    totalLectures: 6,
    totalDuration: "1hr 5min",
    totalMinutes: 65,
    lectures: generateLectures(16, 6, [
      "Introduction to Seaborn",
      "Distribution Plots",
      "Categorical Plots",
      "Heatmaps",
      "Pair Plots and Joint Plots",
      "Styling and Themes",
    ], 11),
  },
  {
    id: 17,
    title: "Exploratory Data Analysis (EDA)",
    totalLectures: 8,
    totalDuration: "2hr",
    totalMinutes: 120,
    lectures: generateLectures(17, 8, [
      "Introduction to EDA",
      "Understanding the Dataset",
      "Univariate Analysis",
      "Bivariate Analysis",
      "Multivariate Analysis",
      "Handling Outliers",
      "Data Cleaning Techniques",
      "EDA Project",
    ], 15),
  },
  {
    id: 18,
    title: "Statistics - Descriptive Statistics",
    totalLectures: 8,
    totalDuration: "1hr 50min",
    totalMinutes: 110,
    lectures: generateLectures(18, 8, [
      "Introduction to Statistics",
      "Measures of Central Tendency",
      "Mean, Median, Mode",
      "Measures of Dispersion",
      "Variance and Standard Deviation",
      "Percentiles and Quartiles",
      "Skewness and Kurtosis",
      "Five Number Summary & Box Plot",
    ], 14),
  },
  {
    id: 19,
    title: "Statistics - Inferential Statistics",
    totalLectures: 10,
    totalDuration: "2hr 20min",
    totalMinutes: 140,
    lectures: generateLectures(19, 10, [
      "Population vs Sample",
      "Normal Distribution",
      "Standard Normal Distribution (Z-score)",
      "Central Limit Theorem",
      "Confidence Intervals",
      "Hypothesis Testing Introduction",
      "Z-Test",
      "T-Test",
      "Chi-Square Test",
      "ANOVA",
    ], 14),
  },
  {
    id: 20,
    title: "Probability",
    totalLectures: 6,
    totalDuration: "1hr 15min",
    totalMinutes: 75,
    lectures: generateLectures(20, 6, [
      "Introduction to Probability",
      "Types of Probability",
      "Conditional Probability",
      "Bayes Theorem",
      "Probability Distributions",
      "Binomial & Poisson Distribution",
    ], 13),
  },
  {
    id: 21,
    title: "Feature Engineering",
    totalLectures: 10,
    totalDuration: "2hr 30min",
    totalMinutes: 150,
    lectures: generateLectures(21, 10, [
      "Introduction to Feature Engineering",
      "Handling Missing Values",
      "Encoding Categorical Variables",
      "One-Hot Encoding",
      "Label Encoding / Ordinal Encoding",
      "Feature Scaling - Standardization",
      "Feature Scaling - Normalization",
      "Handling Imbalanced Dataset",
      "SMOTE Technique",
      "Feature Engineering Practice",
    ], 15),
  },
  {
    id: 22,
    title: "Feature Selection",
    totalLectures: 6,
    totalDuration: "1hr 20min",
    totalMinutes: 80,
    lectures: generateLectures(22, 6, [
      "Introduction to Feature Selection",
      "Filter Methods",
      "Wrapper Methods",
      "Embedded Methods",
      "Variance Threshold",
      "Correlation Matrix",
    ], 13),
  },
  {
    id: 23,
    title: "Introduction to Machine Learning",
    totalLectures: 5,
    totalDuration: "55min",
    totalMinutes: 55,
    lectures: generateLectures(23, 5, [
      "What is Machine Learning?",
      "Types of ML - Supervised, Unsupervised, Reinforcement",
      "ML Workflow / Pipeline",
      "Bias-Variance Tradeoff",
      "Overfitting and Underfitting",
    ], 11),
  },
  {
    id: 24,
    title: "Linear Regression",
    totalLectures: 10,
    totalDuration: "2hr 30min",
    totalMinutes: 150,
    lectures: generateLectures(24, 10, [
      "Introduction to Linear Regression",
      "Simple Linear Regression",
      "Gradient Descent",
      "Math Behind Linear Regression",
      "Cost Function (MSE)",
      "Multiple Linear Regression",
      "Assumptions of Linear Regression",
      "R-squared and Adjusted R-squared",
      "Implementation with Scikit-Learn",
      "Linear Regression Project",
    ], 15),
  },
  {
    id: 25,
    title: "Ridge and Lasso Regression",
    totalLectures: 6,
    totalDuration: "1hr 20min",
    totalMinutes: 80,
    lectures: generateLectures(25, 6, [
      "Regularization Introduction",
      "L1 Regularization (Lasso)",
      "L2 Regularization (Ridge)",
      "Elastic Net Regression",
      "Math Behind Ridge & Lasso",
      "Implementation and Comparison",
    ], 13),
  },
  {
    id: 26,
    title: "Logistic Regression",
    totalLectures: 8,
    totalDuration: "2hr",
    totalMinutes: 120,
    lectures: generateLectures(26, 8, [
      "Introduction to Logistic Regression",
      "Sigmoid Function",
      "Cost Function for Logistic Regression",
      "Gradient Descent for Logistic",
      "Math Behind Logistic Regression",
      "Binary Classification",
      "Multiclass Classification",
      "Implementation & Project",
    ], 15),
  },
  {
    id: 27,
    title: "Decision Trees",
    totalLectures: 8,
    totalDuration: "1hr 50min",
    totalMinutes: 110,
    lectures: generateLectures(27, 8, [
      "Introduction to Decision Trees",
      "Entropy",
      "Information Gain",
      "Gini Impurity",
      "Decision Tree for Classification",
      "Decision Tree for Regression",
      "Pruning Techniques",
      "Implementation",
    ], 14),
  },
  {
    id: 28,
    title: "Random Forest",
    totalLectures: 6,
    totalDuration: "1hr 20min",
    totalMinutes: 80,
    lectures: generateLectures(28, 6, [
      "Introduction to Ensemble Methods",
      "Bagging Concept",
      "Random Forest Algorithm",
      "Feature Importance",
      "Hyperparameter Tuning",
      "Implementation",
    ], 13),
  },
  {
    id: 29,
    title: "Support Vector Machines (SVM)",
    totalLectures: 8,
    totalDuration: "1hr 45min",
    totalMinutes: 105,
    lectures: generateLectures(29, 8, [
      "Introduction to SVM",
      "Hyperplane and Margin",
      "Hard Margin SVM",
      "Soft Margin SVM",
      "Kernel Trick",
      "RBF Kernel",
      "SVM for Regression",
      "Implementation",
    ], 13),
  },
  {
    id: 30,
    title: "K-Nearest Neighbors (KNN)",
    totalLectures: 5,
    totalDuration: "55min",
    totalMinutes: 55,
    lectures: generateLectures(30, 5, [
      "Introduction to KNN",
      "Distance Metrics",
      "Choosing K Value",
      "KNN for Classification & Regression",
      "Implementation",
    ], 11),
  },
  {
    id: 31,
    title: "Naive Bayes",
    totalLectures: 5,
    totalDuration: "50min",
    totalMinutes: 50,
    lectures: generateLectures(31, 5, [
      "Introduction to Naive Bayes",
      "Bayes Theorem Revisited",
      "Gaussian Naive Bayes",
      "Multinomial Naive Bayes",
      "Implementation",
    ], 10),
  },
  {
    id: 32,
    title: "K-Means Clustering",
    totalLectures: 6,
    totalDuration: "1hr 10min",
    totalMinutes: 70,
    lectures: generateLectures(32, 6, [
      "Introduction to Clustering",
      "K-Means Algorithm",
      "Elbow Method",
      "Silhouette Score",
      "K-Means++ Initialization",
      "Implementation",
    ], 12),
  },
  {
    id: 33,
    title: "Hierarchical Clustering",
    totalLectures: 4,
    totalDuration: "45min",
    totalMinutes: 45,
    lectures: generateLectures(33, 4, [
      "Agglomerative Clustering",
      "Dendrograms",
      "Linkage Methods",
      "Implementation",
    ], 11),
  },
  {
    id: 34,
    title: "DBSCAN Clustering",
    totalLectures: 3,
    totalDuration: "30min",
    totalMinutes: 30,
    lectures: generateLectures(34, 3, [
      "Introduction to DBSCAN",
      "Epsilon and MinPoints",
      "Implementation",
    ], 10),
  },
  {
    id: 35,
    title: "PCA - Dimensionality Reduction",
    totalLectures: 5,
    totalDuration: "1hr",
    totalMinutes: 60,
    lectures: generateLectures(35, 5, [
      "Curse of Dimensionality",
      "Introduction to PCA",
      "Math Behind PCA",
      "Eigen Vectors and Eigen Values",
      "Implementation",
    ], 12),
  },
  {
    id: 36,
    title: "Model Evaluation Metrics",
    totalLectures: 8,
    totalDuration: "1hr 30min",
    totalMinutes: 90,
    lectures: generateLectures(36, 8, [
      "Confusion Matrix",
      "Accuracy, Precision, Recall",
      "F1 Score",
      "ROC-AUC Curve",
      "Classification Report",
      "MAE, MSE, RMSE",
      "R-squared Score",
      "Cross Validation",
    ], 11),
  },
  {
    id: 37,
    title: "Hyperparameter Tuning",
    totalLectures: 4,
    totalDuration: "45min",
    totalMinutes: 45,
    lectures: generateLectures(37, 4, [
      "GridSearchCV",
      "RandomizedSearchCV",
      "Bayesian Optimization",
      "Practice",
    ], 11),
  },
  {
    id: 38,
    title: "Ensemble Methods - Boosting",
    totalLectures: 8,
    totalDuration: "1hr 50min",
    totalMinutes: 110,
    lectures: generateLectures(38, 8, [
      "Introduction to Boosting",
      "AdaBoost",
      "Gradient Boosting",
      "Math Behind Gradient Boosting",
      "XGBoost",
      "XGBoost Implementation",
      "LightGBM",
      "CatBoost",
    ], 14),
  },
  {
    id: 39,
    title: "End to End Machine Learning Project 1",
    totalLectures: 8,
    totalDuration: "2hr",
    totalMinutes: 120,
    lectures: generateLectures(39, 8, [
      "Problem Statement",
      "Data Collection",
      "EDA",
      "Feature Engineering",
      "Model Selection",
      "Model Training",
      "Model Evaluation",
      "Prediction Pipeline",
    ], 15),
  },
  {
    id: 40,
    title: "End to End Machine Learning Project 2",
    totalLectures: 8,
    totalDuration: "2hr",
    totalMinutes: 120,
    lectures: generateLectures(40, 8, [
      "Problem Statement & Data",
      "Data Preprocessing",
      "Feature Engineering",
      "Model Building",
      "Hyperparameter Tuning",
      "Model Deployment Setup",
      "Flask Web App",
      "Deployment",
    ], 15),
  },
  {
    id: 41,
    title: "Introduction to Deep Learning",
    totalLectures: 5,
    totalDuration: "1hr",
    totalMinutes: 60,
    lectures: generateLectures(41, 5, [
      "What is Deep Learning?",
      "Biological vs Artificial Neuron",
      "Perceptron",
      "Multi-layer Perceptron",
      "Forward Propagation",
    ], 12),
  },
  {
    id: 42,
    title: "Artificial Neural Networks (ANN)",
    totalLectures: 10,
    totalDuration: "2hr 30min",
    totalMinutes: 150,
    lectures: generateLectures(42, 10, [
      "ANN Architecture",
      "Activation Functions - Sigmoid",
      "Activation Functions - ReLU, Tanh",
      "Activation Functions - Softmax",
      "Forward Propagation Deep Dive",
      "Backpropagation",
      "Chain Rule and Derivatives",
      "Weight Initialization",
      "ANN Implementation with TensorFlow",
      "ANN Project",
    ], 15),
  },
  {
    id: 43,
    title: "Loss Functions",
    totalLectures: 5,
    totalDuration: "55min",
    totalMinutes: 55,
    lectures: generateLectures(43, 5, [
      "Binary Cross Entropy",
      "Categorical Cross Entropy",
      "Mean Squared Error",
      "Huber Loss",
      "Custom Loss Functions",
    ], 11),
  },
  {
    id: 44,
    title: "Optimizers",
    totalLectures: 7,
    totalDuration: "1hr 30min",
    totalMinutes: 90,
    lectures: generateLectures(44, 7, [
      "Gradient Descent Revisited",
      "Stochastic Gradient Descent",
      "Mini-Batch Gradient Descent",
      "Momentum",
      "RMSProp",
      "Adam Optimizer",
      "Learning Rate Scheduling",
    ], 13),
  },
  {
    id: 45,
    title: "Regularization in Deep Learning",
    totalLectures: 5,
    totalDuration: "50min",
    totalMinutes: 50,
    lectures: generateLectures(45, 5, [
      "Overfitting in Neural Networks",
      "Dropout",
      "L1 and L2 Regularization",
      "Batch Normalization",
      "Early Stopping",
    ], 10),
  },
  {
    id: 46,
    title: "Convolutional Neural Networks (CNN)",
    totalLectures: 10,
    totalDuration: "2hr 30min",
    totalMinutes: 150,
    lectures: generateLectures(46, 10, [
      "Introduction to CNN",
      "Convolution Operation",
      "Filters and Feature Maps",
      "Padding and Stride",
      "Pooling Layers",
      "CNN Architecture",
      "LeNet, AlexNet",
      "VGG and ResNet",
      "Transfer Learning",
      "CNN Project - Image Classification",
    ], 15),
  },
  {
    id: 47,
    title: "Recurrent Neural Networks (RNN)",
    totalLectures: 6,
    totalDuration: "1hr 20min",
    totalMinutes: 80,
    lectures: generateLectures(47, 6, [
      "Introduction to RNN",
      "Sequence Data",
      "Vanishing Gradient Problem",
      "RNN Architecture",
      "BPTT (Backpropagation Through Time)",
      "Implementation",
    ], 13),
  },
  {
    id: 48,
    title: "LSTM and GRU",
    totalLectures: 6,
    totalDuration: "1hr 15min",
    totalMinutes: 75,
    lectures: generateLectures(48, 6, [
      "LSTM Architecture",
      "Forget Gate, Input Gate, Output Gate",
      "LSTM Implementation",
      "GRU Architecture",
      "GRU vs LSTM",
      "Time Series Forecasting Project",
    ], 13),
  },
  {
    id: 49,
    title: "Introduction to NLP",
    totalLectures: 5,
    totalDuration: "55min",
    totalMinutes: 55,
    lectures: generateLectures(49, 5, [
      "What is NLP?",
      "NLP Applications",
      "NLP Pipeline",
      "Text Data Challenges",
      "NLP Libraries Overview",
    ], 11),
  },
  {
    id: 50,
    title: "Text Preprocessing",
    totalLectures: 8,
    totalDuration: "1hr 45min",
    totalMinutes: 105,
    lectures: generateLectures(50, 8, [
      "Tokenization",
      "Stopword Removal",
      "Stemming",
      "Lemmatization",
      "Bag of Words",
      "TF-IDF",
      "N-grams",
      "Text Preprocessing Pipeline",
    ], 13),
  },
  {
    id: 51,
    title: "Word Embeddings",
    totalLectures: 6,
    totalDuration: "1hr 20min",
    totalMinutes: 80,
    lectures: generateLectures(51, 6, [
      "Introduction to Word Embeddings",
      "Word2Vec - CBOW",
      "Word2Vec - Skip-gram",
      "GloVe",
      "FastText",
      "Implementation",
    ], 13),
  },
  {
    id: 52,
    title: "Transformers and Attention Mechanism",
    totalLectures: 8,
    totalDuration: "2hr",
    totalMinutes: 120,
    lectures: generateLectures(52, 8, [
      "Attention Mechanism",
      "Self-Attention",
      "Multi-Head Attention",
      "Transformer Architecture",
      "Positional Encoding",
      "Encoder-Decoder",
      "BERT Overview",
      "GPT Overview",
    ], 15),
  },
  {
    id: 53,
    title: "Sentiment Analysis Project",
    totalLectures: 6,
    totalDuration: "1hr 30min",
    totalMinutes: 90,
    lectures: generateLectures(53, 6, [
      "Problem Statement",
      "Data Collection",
      "Text Preprocessing",
      "Feature Extraction",
      "Model Building",
      "Evaluation and Deployment",
    ], 15),
  },
  {
    id: 54,
    title: "Text Classification Project",
    totalLectures: 6,
    totalDuration: "1hr 30min",
    totalMinutes: 90,
    lectures: generateLectures(54, 6, [
      "Problem Statement",
      "Data Preprocessing",
      "TF-IDF and Word Embeddings",
      "Model Training",
      "Model Evaluation",
      "Deployment",
    ], 15),
  },
  {
    id: 55,
    title: "Named Entity Recognition",
    totalLectures: 5,
    totalDuration: "1hr",
    totalMinutes: 60,
    lectures: generateLectures(55, 5, [
      "Introduction to NER",
      "NER Approaches",
      "SpaCy for NER",
      "Custom NER Training",
      "NER Project",
    ], 12),
  },
  {
    id: 56,
    title: "NLP End to End Projects",
    totalLectures: 8,
    totalDuration: "2hr",
    totalMinutes: 120,
    lectures: generateLectures(56, 8, [
      "Project 1 - Text Summarization",
      "Project 1 - Implementation",
      "Project 2 - Chatbot Basics",
      "Project 2 - Implementation",
      "Project 3 - Language Translation",
      "Project 3 - Implementation",
      "Project Review",
      "Best Practices",
    ], 15),
  },
  {
    id: 57,
    title: "Introduction to MLOps",
    totalLectures: 5,
    totalDuration: "55min",
    totalMinutes: 55,
    lectures: generateLectures(57, 5, [
      "What is MLOps?",
      "MLOps vs DevOps",
      "ML Pipeline",
      "Model Lifecycle Management",
      "MLOps Tools Overview",
    ], 11),
  },
  {
    id: 58,
    title: "MLflow",
    totalLectures: 6,
    totalDuration: "1hr 20min",
    totalMinutes: 80,
    lectures: generateLectures(58, 6, [
      "Introduction to MLflow",
      "Experiment Tracking",
      "Model Registry",
      "MLflow Projects",
      "MLflow Models",
      "Implementation",
    ], 13),
  },
  {
    id: 59,
    title: "DVC (Data Version Control)",
    totalLectures: 4,
    totalDuration: "45min",
    totalMinutes: 45,
    lectures: generateLectures(59, 4, [
      "Introduction to DVC",
      "Version Control for Data",
      "DVC Pipelines",
      "Implementation",
    ], 11),
  },
  {
    id: 60,
    title: "Docker for ML",
    totalLectures: 5,
    totalDuration: "55min",
    totalMinutes: 55,
    lectures: generateLectures(60, 5, [
      "Introduction to Docker",
      "Dockerfile",
      "Docker Images and Containers",
      "Containerizing ML Models",
      "Docker Compose",
    ], 11),
  },
  {
    id: 61,
    title: "CI/CD for ML",
    totalLectures: 5,
    totalDuration: "55min",
    totalMinutes: 55,
    lectures: generateLectures(61, 5, [
      "Introduction to CI/CD",
      "GitHub Actions",
      "Automated Testing",
      "Automated Training Pipeline",
      "Implementation",
    ], 11),
  },
  {
    id: 62,
    title: "Cloud Deployment (AWS/GCP/Azure)",
    totalLectures: 8,
    totalDuration: "2hr",
    totalMinutes: 120,
    lectures: generateLectures(62, 8, [
      "Deployment Options Overview",
      "Flask/FastAPI for ML",
      "AWS EC2 Deployment",
      "AWS S3 and ECR",
      "GCP Deployment",
      "Azure Deployment",
      "Streamlit Deployment",
      "End to End Deployment Project",
    ], 15),
  },
  {
    id: 63,
    title: "Final Capstone Projects & Wrap Up",
    totalLectures: 8,
    totalDuration: "2hr",
    totalMinutes: 120,
    lectures: generateLectures(63, 8, [
      "Capstone Project 1 - Planning",
      "Capstone Project 1 - Implementation",
      "Capstone Project 1 - Deployment",
      "Capstone Project 2 - Planning",
      "Capstone Project 2 - Implementation",
      "Capstone Project 2 - Deployment",
      "Career Guidance & Next Steps",
      "Course Completion",
    ], 15),
  },
];

export const TOTAL_COURSE_LECTURES = COURSE_SECTIONS.reduce((sum, s) => sum + s.totalLectures, 0);
export const TOTAL_COURSE_MINUTES = COURSE_SECTIONS.reduce((sum, s) => sum + s.totalMinutes, 0);
export const TOTAL_COURSE_HOURS = 99; // As per Udemy listing
